### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by AmitMY** [seancook/docker-openpose-cpu#1] opened 2019-07-09 12:26 UTC
When running build, I'm getting the following errors.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/5757359/60887737-c1e24300-a25d-11e9-8c38-cb45f7c923e8.png">

Maybe need to tie the caffe version to a specific one? or anything else? I haven't managed to compile this myself.

*BTW, if you upload this to DockerHub all we'll need to do is pull once. Thanks so much for this!

**Comment by jonathanmv** [comment] 2020-02-21 23:12
Hey @AmitMY,
I was reproducing step by step every command in the Dockerfile and was able to get the same error. After googling the `Killed (program cc1plus)` error I found [this suggestion](https://stackoverflow.com/a/35011967/1128216) which helped me complete the `make -j` command.

I then changed the Dockerfile to include `make -j 4 #yolo` instead of `make -j #yolo` and was able to build the docker image and run it successfully. 

I created this PR https://github.com/seancook/docker-openpose-cpu/pull/2

**Comment by AmitMY** [comment] 2020-02-22 10:47
Feel free to use https://github.com/AmitMY/pose-docker instead, I managed to build it on various machines

**Comment by jonathanmv** [comment] 2020-02-22 11:05
Thanks for the reference @AmitMY, however I’m looking for a cpu only image and the one pointed by you requires Nvidia drivers. 

Since you’ve managed to build it on various machines, I think you should close this issue. What do you think?

Thanks again for your reply

**Closed as completed** 2020-02-22 11:16 UTC
